#!/usr/bin/env bash

set -e

pushd ~/nixos/

if git diff --quiet '*.nix'; then
    echo "No changes detected"
    popd
    exit 0
fi

git diff -U0 '*.nix'

echo "Rebuilding..."

sudo nixos-rebuild switch --flake .#nixos &> nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)
current=$(nixos-rebuild list-generations | grep current)

git commit -am "$current"

popd

echo "Rebuild Successful, changes applied"
