#!/usr/bin/env bash
set -e
set -o pipefail

pushd ~/nixos/

# if git diff --quiet '*.nix'; then
#     echo "No changes detected"
#     popd
#     exit 0
# fi

git diff -U0 '*.nix'

echo "Rebuilding..."

sudo nixos-rebuild switch --flake .#nixos | tee nixos-switch.log

# current=$(nixos-rebuild list-generations | grep True)
# printf "Curent generation: %s\n" "$current"
# git commit -am "$current"
#
popd

echo "Rebuild Successful, changes applied"
