#!/usr/bin/env bash
set -e
set -o pipefail

pushd ~/nixos/

git diff -U0 '*.nix'

echo "Rebuilding..."

sudo nixos-rebuild switch --flake .#nixos | tee nixos-switch.log

popd

echo "Rebuild Successful, changes applied"
